# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6640b1b2966a05f33380b8fb7f23dfe3"
name = "Gallery-flow"
handle = "gallery-flow"
application_url = "https://unknown-powered-gardening-projectors.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers, unauthenticated_read_customers,unauthenticated_write_customers,read_themes,write_themes"



[auth]
redirect_urls = ["https://unknown-powered-gardening-projectors.trycloudflare.com/auth/callback", "https://unknown-powered-gardening-projectors.trycloudflare.com/auth/shopify/callback", "https://unknown-powered-gardening-projectors.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
